# Generated by Django 3.1.2 on 2020-10-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_api', '0002_auto_20201022_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='docker_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='path',
            field=models.CharField(max_length=100),
        ),
    ]
