# Generated by Django 3.1.2 on 2020-10-22 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_api', '0003_auto_20201022_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_visible',
            field=models.BooleanField(blank='true', default=True),
            preserve_default=False,
        ),
    ]
